# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "line-bedrock-bot"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "line-bedrock-bot"
parameter_overrides = "LineToken=\"SFsh6ogb4X/KagEQQDcONKgxh8qVP6DSReB7sihWyxbwWUc/UsbcWibSzkvjA/1pi2k71JYQjpOwHoP6+q68tSPv0U/69sjb7DhUqMlMQWEAAEnfbhqpllxMJ7hDWjET/8ZVCzwJA28FsuBFzaNxGwdB04t89/1O/w1cDnyilFU=\" LineSecret=\"407808158af3aacda966f6b43a9f880e\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
